"""Trace how a HyperFrames scene workspace implements its direction events.

HyperFrames scenes keep the visual-direction contract. Before the clip renders,
``write_bridge`` writes ``om-direction.js`` into the scene workspace with the
scene's visual_timeline events in scene-local seconds, and ``trace_workspace``
requires that every event is placed by the authored GSAP code
(``OM.at("<event id>")`` or ``data-om-event="<event id>"``).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Optional

BRIDGE_JS = "om-direction.js"
BRIDGE_JSON = "om-direction.json"
_REF_RE = re.compile(r"""OM\.at\(\s*["']([^"']+)["']\s*\)|data-om-event\s*=\s*["']([^"']+)["']""")
_SCRIPT_RE = re.compile(r"""<script[^>]+src\s*=\s*["'](?:\./)?om-direction\.js["']""", re.I)
_DURATION_RE = re.compile(r"""data-composition-id\s*=\s*["']root["'][^>]*?data-duration\s*=\s*["']([\d.]+)["']"""
                          r"""|data-duration\s*=\s*["']([\d.]+)["'][^>]*?data-composition-id\s*=\s*["']root["']""", re.S)


def hyperframes_cuts(edit_decisions: dict[str, Any]) -> list[dict[str, Any]]:
    return [c for c in edit_decisions.get("cuts") or [] if (c.get("runtime") or "").lower() == "hyperframes"]


def scene_events(timeline: Optional[dict[str, Any]], cut: dict[str, Any]) -> list[dict[str, Any]]:
    """visual_timeline events executed by this scene cut, in scene-local seconds."""
    if not timeline:
        return []
    start, end = float(cut["in_seconds"]), float(cut["out_seconds"])
    sid = cut.get("scene_id")
    out = []
    for ev in timeline.get("events") or []:
        t = float(ev["time_seconds"])
        mine = ev.get("scene_id") == sid if sid else start - 1e-3 <= t < end
        if not mine:
            continue
        out.append({
            "id": ev["id"],
            "t": round(max(0.0, t - start), 3),
            "duration": float(ev.get("duration_seconds") or 0.0),
            "operation": ev.get("operation"),
            "target": ev.get("target"),
            "model_id": ev.get("model_id"),
            "params": ev.get("params") or {},
            "anchor": (ev.get("anchor") or {}).get("text"),
        })
    return sorted(out, key=lambda e: (e["t"], e["id"]))


def without_scene_events(timeline: Optional[dict[str, Any]], cuts: list[dict[str, Any]]) -> Optional[dict[str, Any]]:
    """The timeline minus the events that HyperFrames scene cuts execute."""
    if not timeline or not cuts:
        return timeline
    owned = {e["id"] for c in cuts for e in scene_events(timeline, c)}
    return {**timeline, "events": [e for e in timeline.get("events") or [] if e["id"] not in owned]}


def write_bridge(workspace: Path, cut: dict[str, Any], events: list[dict[str, Any]]) -> Path:
    """Write the generated ``om-direction.js`` (and .json) into the scene workspace."""
    data = {
        "scene_id": cut.get("scene_id"),
        "cut_id": cut.get("id"),
        "duration": round(float(cut["out_seconds"]) - float(cut["in_seconds"]), 3),
        "events": events,
    }
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    (workspace / BRIDGE_JSON).write_text(payload, encoding="utf-8")
    js = (
        "// Generated by OpenMontage video_compose from visual_timeline. Do not edit.\n"
        "// Place every event with OM.at(\"<event id>\") (scene-local seconds) on your GSAP timeline.\n"
        f"window.OM_DIRECTION = {payload};\n"
        "window.OM = {\n"
        "  direction: window.OM_DIRECTION,\n"
        "  at: function (id) {\n"
        "    var ev = window.OM_DIRECTION.events.find(function (e) { return e.id === id; });\n"
        "    if (!ev) { throw new Error('OpenMontage: unknown direction event ' + id); }\n"
        "    return ev.t;\n"
        "  },\n"
        "  event: function (id) {\n"
        "    return window.OM_DIRECTION.events.find(function (e) { return e.id === id; }) || null;\n"
        "  }\n"
        "};\n"
    )
    path = workspace / BRIDGE_JS
    path.write_text(js, encoding="utf-8")
    return path


def root_duration(workspace: Path) -> Optional[float]:
    entry = workspace / "index.html"
    if not entry.is_file():
        return None
    m = _DURATION_RE.search(entry.read_text(encoding="utf-8", errors="ignore"))
    return float(m.group(1) or m.group(2)) if m else None


def trace_workspace(workspace: Path, events: list[dict[str, Any]], expected_duration: Optional[float] = None
                    ) -> dict[str, Any]:
    """Map every scene event to the authored HyperFrames code that places it."""
    hard: list[str] = []
    refs: dict[str, list[str]] = {}
    entry = workspace / "index.html"
    if not entry.is_file():
        return {"hard_failures": [f"no index.html in {workspace}"], "events": [], "implemented": 0}
    html = entry.read_text(encoding="utf-8", errors="ignore")
    if events and not _SCRIPT_RE.search(html):
        hard.append(f'{entry.name} does not load {BRIDGE_JS}: add <script src="{BRIDGE_JS}"></script> before '
                    f"your timeline script")
    for path in sorted(workspace.rglob("*")):
        if (path.suffix.lower() not in (".html", ".js") or path.name == BRIDGE_JS
                or "node_modules" in path.parts or "renders" in path.parts):
            continue
        for lineno, line in enumerate(path.read_text(encoding="utf-8", errors="ignore").splitlines(), 1):
            for m in _REF_RE.finditer(line):
                eid = m.group(1) or m.group(2)
                refs.setdefault(eid, []).append(f"{path.relative_to(workspace).as_posix()}:{lineno}")
    known = {e["id"] for e in events}
    rows = []
    for ev in events:
        where = refs.get(ev["id"], [])
        rows.append({"event_id": ev["id"], "t": ev["t"], "implemented": bool(where), "where": where})
        if not where:
            hard.append(f"{ev['id']} ({ev['operation']} {ev['target']}) at scene time {ev['t']}s is not placed in "
                        f"the HyperFrames code (use OM.at(\"{ev['id']}\"))")
    for eid in sorted(set(refs) - known):
        hard.append(f"code references direction event {eid!r} that this scene does not have ({refs[eid][0]})")
    if expected_duration is not None:
        dur = root_duration(workspace)
        if dur is None:
            hard.append("root composition has no data-duration")
        elif abs(dur - expected_duration) > 0.05:
            hard.append(f"root data-duration {dur}s does not match the scene cut ({expected_duration:.3f}s)")
    return {"hard_failures": hard, "events": rows, "implemented": sum(r["implemented"] for r in rows)}
